AWSTemplateFormatVersion: 2010-09-09
Description: >-
  public-api

Transform:
- AWS::Serverless-2016-10-31

Parameters:

  Stage:
    Type: String
    Description: Runtime environment
    Default: staging

Resources:
  SimulationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type,Accept'"
        AllowOrigin: "'*'"

  GetPowerDistributors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/src/application/web/handlers/get-power-distributors.handler
      FunctionName: PublicApi-GetPowerDistributors
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref SimulationApi
            Path: /simulations/power-distributors/{zip}
            Method: GET
      Environment:
        Variables:
          STAGE: !Ref Stage
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/application/web/handlers/get-power-distributors.ts

  CalculateSimulation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/src/application/web/handlers/calculate-simulation.handler
      FunctionName: PublicApi-CalculateSimulation
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref SimulationApi
            Path: /simulations/calculate
            Method: POST
    Environment:
      Variables:
        STAGE: !Ref Stage
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/application/web/handlers/calculate-simulation.ts
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SimulationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
